### PR TITLE
Add reporting api

### PR DESCRIPTION
**Pull request by nickcoyne**
Adds support for calls to https://developers.quaderno.io/api/#report-requests

### CODE REVIEW

**Comment by polimorfico** [comment]
Hey Nick! Thanks for the contribution. Could you please add a simple test? Thanks!

**Comment by nickcoyne** [comment]
@polimorfico I can't get VCR to record from my sandbox url. It fails during auth:

```
    Failure/Error:
       response = post("#{authentication[:url]}#{api_model.api_path}.json",
         body: params.to_json,
         basic_auth: authentication[:basic_auth],
         headers: default_headers.merge(authentication[:headers]).merge('Content-Type' => 'application/json')
       )
     
     NoMethodError:
       undefined method `<<' for #<Hash:0x00007fc65c3c0f80>
       Did you mean?  <
     # ./lib/quaderno-ruby/behavior/crud.rb:74:in `create'
     # ./spec/unit/test_quaderno_report_requests.rb:34:in `block (4 levels) in <top (required)>'
     # ./spec/unit/test_quaderno_report_requests.rb:33:in `block (3 levels) in <top (required)>'
```

**Comment by xxswingxx** [comment]
Hey @nickcoyne, could you create a branch with your specs and let me check it?

**Comment by xxswingxx** [comment]
After writing some tests myself I think it's an issue with the webmock version. I think it's safe to merge @polimorfico

**Pull request merged**
